K: 20
THRES: 1e-9
N_BATCH: 500
exe: "build/pquant"
OUT_DIR: "out_sim_read_241007"
GENE_PATH: "/gpfs/commons/groups/gursoy_lab/cwalker/projects/pquant/workflow/data/reference/pquant/gencode.v44.basic.annotation.subset.exons.fa"
READ_PATH: "/gpfs/commons/groups/gursoy_lab/cwalker/projects/pquant/workflow/data/encode/original/ENCLB059ZZZ/ENCLB059ZZZ.concat.fastq"
# option for using simulated reads
sr: true

slurm:
  step1:
    mem: "250G"
    cpus: 8
  step2:
    mem: "1G"
    cpus: 1
  step3:
    mem: "200G"
    cpus: 8
  step4:
    mem: "200G"
    cpus: 8
  step5:
    mem: "200G"
    cpus: 8