K: 20
THRES: 1e-9
N_BATCH: 500
exe: "build/pquant"
OUT_DIR: "out/test"
GENE_PATH: # set your gene path
READ_PATH: # set your read path

# option for using simulated reads
sr: false

# option for quality control
QC: 5
TPM_THRES: 1.0


slurm:
  step1:
    mem: "150G"
    cpus: 8
  step2:
    mem: "1G"
    cpus: 1
  step3:
    mem: "50G"
    cpus: 8
  step4:
    mem: "100G"
    cpus: 8
  step5:
    mem: "80G"
    cpus: 8
