K: 20
THRES: 1e-9
N_BATCH: 3
exe: "build/pquant"
OUT_DIR: "out_sim_read_241007"
GENE_PATH: "dataset/five_genes/five_gene_reference.fa"
READ_PATH: "dataset/five_genes/five_gene_reads.fa"
# option for using simulated reads
sr: false

slurm:
  step1:
    mem: "200G"
    cpus: 8
  step2:
    mem: "1G"
    cpus: 1
  step3:
    mem: "200G"
    cpus: 8
  step4:
    mem: "200G"
    cpus: 8
  step5:
    mem: "200G"
    cpus: 8